apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mlflow.fullname" . }}-env-configmap
  labels:
    app: {{ template "mlflow.name" . }}
    chart: {{ template "mlflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.backendStore.postgres.enabled }}
  PGHOST: {{ required "postgres host must be specified" .Values.backendStore.postgres.host }}
  PGPORT: {{ required "postgres port must be specified" .Values.backendStore.postgres.port | quote }}
  PGDATABASE: {{ required "postgres database must be specified" .Values.backendStore.postgres.database }}
{{- end }}
{{- if .Values.backendStore.mysql.enabled }}
  MYSQL_HOST: {{ required "mysql host must be specified" .Values.backendStore.mysql.host }}
  MYSQL_TCP_PORT: {{ required "mysql port must be specified" .Values.backendStore.mysql.port | quote }}
  MYSQL_DATABASE: {{ required "mysql database must be specified" .Values.backendStore.mysql.database }}
{{- end }}
